### ISSUE TITLE
Update for module3_images.md

### ISSUE THREAD

**Issue by stevshil** [nicktodd/dockerlabs#1]
Part 2
Before running this lab we should do a cd to return home, otherwise they'll be making the directory in the current git repository.

After doing cd to home the **md** command needs to be **mkdir**

**Comment by stevshil** [comment]
Part 1

Instead of the chmod a+x and the ./mvnw

We can instead use a docker compile container as follows;

```
paymentgateway-standalone]$ docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src maven:3.9.3-amazoncorretto-8 mvn package
```

or using a smaller container image

```
docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src maven:3.9.3-eclipse-temurin-20-alpine mvn package
```

**Comment by vppmatt** [comment]
@stevshil This is neater / less work but I wonder if it's a bit confusing for those new to docker - that's a tough single line to interpret. The current steps (at least to a developer!) would make it clearer what is happening / how it works. It also means that they are still doing the git clone manually first, so the machine needs some software (git) installed on it, and repeating the exercise after changes is a multi-step process. How about we create 2 versions of this lab, one that uses your suggestion (which might be better for PS) and one which keeps the current set up (which might be better for devs)?

**Comment by stevshil** [comment]
They still need to do the git clone.  What this is doing is saving having to install Java on your machine, or better still, what if you need to see if it compiles with an older version, but don't want to uninstall and reinstall or mess around with the environment.
We can shorten the command to;
```
git clone https://github.com/vppmatt/paymentgateway-standalone.git
cd paymentgateway-standalone
docker run -it --rm -v $PWD:/src -w /src maven:3.9.3-eclipse-temurin-20-alpine mvn package
```

Then part 2 would still need to change the **md** to mkdir with a **cd** on its own before hand.
